version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  target-branch: java8
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  target-branch: java11
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  target-branch: java17
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  target-branch: java21
