version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  target-branch: java16
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  target-branch: java17
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  target-branch: java15
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  target-branch: java8
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  target-branch: java11
